### ISSUE TITLE
Reduce woodpecker noice

### ISSUE THREAD

**Issue by ValenberghsSven** [mu-semtech/mu-cli#29]
Woodpecker .yml files are not accurate.

A feature branch PR is triggering all checks
![Image](https://github.com/user-attachments/assets/1d93ffe3-e74f-4c2a-80d8-f8c7bd5bb007)

```
pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
    when:
      event: push
      branch: feature/*
```

should have no indentation for the `when` part

```
pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
```

Same for all woodpecker files in this repo.
Feature branches will trigger only feature builds.
Pushes to master will trigger only latest builds
Tags will trigger only tag builds

**Comment by ValenberghsSven** [comment]
Update: suggested solution no longer correct due to updated woodpecker infrastructure

```
steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [feature/*]
```
